//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class equipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public equipment()
        {
            this.office = new HashSet<office>();
        }
    
        public int id { get; set; }
        public string name_of { get; set; }
        public int quantity { get; set; }
        public Nullable<int> type_of { get; set; }
        public Nullable<int> respons_pers { get; set; }
        public Nullable<int> number { get; set; }
        public int price { get; set; }
    
        public virtual respons_person respons_person { get; set; }
        public virtual type_of_equip type_of_equip { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<office> office { get; set; }
    }
}
